apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret-prd
  namespace: default
spec:
  secretName: tls-secret-prd
  dnsNames:
    - mario.yusufhaydar.com
    - tetris.yusufhaydar.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
